<?php

declare(strict_types=1);

return [
    'name' => 'Social',
    'SEED_SOCIAL_GROUP_POSTS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_GROUP_USERS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_GROUPS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_PAGE_FOLLOWERS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_PAGE_POSTS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_PAGES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_POLL_ITEM_VOTES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_POLL_ITEMS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_POLLS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_USER_FOLLOWERS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_USER_PROFILES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_SOCIAL_WORKSPACES_COUNT' => env('SEEDER_DEFAULT', 3),
];
