<?php

return [
    'name' => 'Social',
    'SEED_SOCIAL_GROUP_POSTS_COUNT' => 3,
    'SEED_SOCIAL_GROUP_USERS_COUNT' => 3,
    'SEED_SOCIAL_GROUPS_COUNT' => 3,
    'SEED_SOCIAL_PAGE_FOLLOWERS_COUNT' => 3,
    'SEED_SOCIAL_PAGE_POSTS_COUNT' => 3,
    'SEED_SOCIAL_PAGES_COUNT' => 3,
    'SEED_SOCIAL_POLL_ITEM_VOTES_COUNT' => 3,
    'SEED_SOCIAL_POLL_ITEMS_COUNT' => 3,
    'SEED_SOCIAL_POLLS_COUNT' => 3,
    'SEED_SOCIAL_USER_FOLLOWERS_COUNT' => 3,
    'SEED_SOCIAL_USER_PROFILES_COUNT' => 3,
    'SEED_SOCIAL_WORKSPACES_COUNT' => 3,
];
